- name: restore /etc/etcd/etcd.conf file
  synchronize:
    src: "{{ backup_srv_path }}/{{ inventory_hostname }}/{{ etcd_config_restore_dir }}/etcd.conf"
    dest: /etc/etcd/etcd.conf
    archive: false
    recursive: true

- name: restore permissions files of /etc/etcd/
  shell: "restorecon -Rv /etc/etcd/"

#TODO: do it idempotent way?
- name: stop etcd service by moving /etc/origin/node/pods/etcd.yaml file
  shell: mv /etc/origin/node/pods/etcd.yaml /root/etcd.yaml

- name: remove all the data
  file:
    path: /var/lib/etcd
    state: absent

- name: create temp directory to store snapshot
  tempfile:
    state: directory
    prefix: "/tmp/etcd-"
  register: tempdir

- name: restore snapshot.db file
  synchronize:
    src: "{{ backup_srv_path }}/{{ groups['etcd'][0] }}/{{ etcd_data_restore_dir }}/snapshot.db"
    dest: "{{ tempdir.path }}"
    archive: false
    recursive: true

- name: get etcd_initial_cluster param for restoring
  shell: "grep -i {{ etcd_initial_cluster_str }} /etc/etcd/etcd.conf | awk -F\"{{ etcd_initial_cluster_str }}\" '{print $2}'"
  register: etcd_initial_cluster

- name: get etcd_initial_cluster_token param for restoring
  shell: "grep -i {{ etcd_initial_cluster_token_str }} /etc/etcd/etcd.conf | awk -F\"{{ etcd_initial_cluster_token_str }}\" '{print $2}'"
  register: etcd_initial_cluster_token

- name: get etcd_initial_advertise_peer_urls param for restoring
  shell: "grep -i {{ etcd_initial_advertise_peer_urls_str }} /etc/etcd/etcd.conf | awk -F\"{{ etcd_initial_advertise_peer_urls_str }}\" '{print $2}'"
  register: etcd_initial_advertise_peer_urls

- name: restore etcd data
  shell: "ETCDCTL_API=3 etcdctl snapshot restore {{ tempdir.path }}/snapshot.db --data-dir /var/lib/etcd/ --name {{ inventory_hostname }} --initial-cluster {{ etcd_initial_cluster.stdout }} --initial-cluster-token {{ etcd_initial_cluster_token.stdout }} --initial-advertise-peer-urls {{ etcd_initial_advertise_peer_urls.stdout }} --skip-hash-check=true"

#TODO: do it idempotent way?
- name: stop etcd service by moving /etc/origin/node/pods/etcd.yaml file
  shell: mv /root/etcd.yaml /etc/origin/node/pods/etcd.yaml
