- include_tasks: prereqs.yml

#TODO: delete this or not?
#- name: restore /etc/origin/master/ files
#  synchronize:
#    src: "{{ backup_srv_path }}/{{ inventory_hostname }}/{{ origin_master_config_dir }}/"
#    dest: "/etc/origin/master/"
#    archive: false
#    recursive: true

- name: restore /etc/origin/master/ files
  synchronize:
    src: "{{ backup_srv_path }}/{{ inventory_hostname }}/{{ origin_master_config_dir }}/{{ item }}"
    dest: "/etc/origin/master/{{ item }}"
    archive: false
    recursive: true
    links: true
  loop:
  - master-config.yaml
  - master.env
  - scheduler.json

- name: restart master api
  shell: "master-restart api"

- name: restart master controllers
  shell: "master-restart controllers"
