- name: cluster backup
  hosts: all
  tasks:
  - import_role:
      name: openshift_facts
      tasks_from: backup

- import_playbook: openshift-node/backup.yml
  tags: node-config
- import_playbook: openshift-etcd/backup.yml
  tags: etcd
