- import_tasks: prereqs.yml
- name: create backup directories
  file:
    path: "{{ backup_srv_path }}/{{ inventory_hostname }}/{{ origin_backup_dir }}"
    state: directory
    recurse: true
  delegate_to: localhost
- name: synchronize /etc/origin contents
  synchronize:
    src: /etc/origin/
    dest: "{{ backup_srv_path }}/{{ inventory_hostname }}/{{ origin_backup_dir }}"
    mode: pull
    archive: false
    recursive: true
    links: true
